### ISSUE TITLE
android can't build arm

### ISSUE THREAD

**Issue by Kao953** [cisco/openh264#2759] opened 2017-06-05 15:47 UTC
I'm trying to build openh264 for arm(and arm64) of android but fail!!
Other platform(x86/x64/mip/mip64) is OK.

OS : Ubuntu 14.04-i386 (hyper-v) 
nasm : 2.10.9

Error message:
`ikaros@ikaros-Virtual-Machine:~/openh264/v1.6/openh264$ make os=android NDKROOT=~/ndk/android-ndk-r14b/ TARGET=android-12 ARCH=arm64 APP_ABI=armeabi NDKLEVEL=21 g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/common_tables.o codec/common/src/common_tables.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/copy_mb.o codec/common/src/copy_mb.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/cp
ikaros@ikaros-Virtual-Machine:~/openh264/v1.6/openh264$ make os=android NDKROOT=~/ndk/android-ndk-r14b/ TARGET=android-12 ARCH=arm64 APP_ABI=armeabi NDKLEVEL=21 g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/common_tables.o codec/common/src/common_tables.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/copy_mb.o codec/common/src/copy_mb.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/cpu.o codec/common/src/cpu.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/crt_util_safe_x.o codec/common/src/crt_util_safe_x.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/deblocking_common.o codec/common/src/deblocking_common.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/expand_pic.o codec/common/src/expand_pic.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/intra_pred_common.o codec/common/src/intra_pred_common.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/mc.o codec/common/src/mc.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/memory_align.o codec/common/src/memory_align.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/sad_common.o codec/common/src/sad_common.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/utils.o codec/common/src/utils.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/welsCodecTrace.o codec/common/src/welsCodecTrace.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/WelsTaskThread.o codec/common/src/WelsTaskThread.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/WelsThread.o codec/common/src/WelsThread.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/WelsThreadLib.o codec/common/src/WelsThreadLib.cpp g++ -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/WelsThreadPool.o codec/common/src/WelsThreadPool.cpp cc -O3 -DNDEBUG -DHAVE_NEON_AARCH64 -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/common/arm64/ -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/arm64/copy_mb_aarch64_neon.o codec/common/arm64/copy_mb_aarch64_neon.S codec/common/arm64/copy_mb_aarch64_neon.S: Assembler messages: codec/common/arm64/copy_mb_aarch64_neon.S:110: Error: no such instruction: sxtw x1,w1'
  codec/common/arm64/copy_mb_aarch64_neon.S:111: Error: no such instruction:sxtw x3,w3' codec/common/arm64/copy_mb_aarch64_neon.S:112: Error: no such instruction: ld1 {v0.8b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:112: Error: no such instruction:ld1 {v1.8b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:112: Error: no such instruction: ld1 {v2.8b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:112: Error: no such instruction:ld1 {v3.8b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:114: Error: no such instruction: st1 {v0.8b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:114: Error: no such instruction:st1 {v1.8b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:114: Error: no such instruction: st1 {v2.8b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:114: Error: no such instruction:st1 {v3.8b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:116: Error: no such instruction: ld1 {v4.8b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:116: Error: no such instruction:ld1 {v5.8b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:116: Error: no such instruction: ld1 {v6.8b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:116: Error: no such instruction:ld1 {v7.8b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:118: Error: no such instruction: st1 {v4.8b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:118: Error: no such instruction:st1 {v5.8b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:118: Error: no such instruction: st1 {v6.8b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:118: Error: no such instruction:st1 {v7.8b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:124: Error: no such instruction: sxtw x1,w1'
  codec/common/arm64/copy_mb_aarch64_neon.S:125: Error: no such instruction:sxtw x3,w3' codec/common/arm64/copy_mb_aarch64_neon.S:126: Error: no such instruction: ld1 {v0.2d},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:126: Error: no such instruction:ld1 {v1.2d},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:126: Error: no such instruction: ld1 {v2.2d},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:126: Error: no such instruction:ld1 {v3.2d},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:128: Error: no such instruction: st1 {v0.2d},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:128: Error: no such instruction:st1 {v1.2d},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:128: Error: no such instruction: st1 {v2.2d},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:128: Error: no such instruction:st1 {v3.2d},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:130: Error: no such instruction: ld1 {v16.2d},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:130: Error: no such instruction:ld1 {v17.2d},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:130: Error: no such instruction: ld1 {v18.2d},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:130: Error: no such instruction:ld1 {v19.2d},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:132: Error: no such instruction: st1 {v16.2d},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:132: Error: no such instruction:st1 {v17.2d},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:132: Error: no such instruction: st1 {v18.2d},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:132: Error: no such instruction:st1 {v19.2d},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:134: Error: no such instruction: ld1 {v0.2d},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:134: Error: no such instruction:ld1 {v1.2d},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:134: Error: no such instruction: ld1 {v2.2d},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:134: Error: no such instruction:ld1 {v3.2d},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:136: Error: no such instruction: st1 {v0.2d},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:136: Error: no such instruction:st1 {v1.2d},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:136: Error: no such instruction: st1 {v2.2d},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:136: Error: no such instruction:st1 {v3.2d},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:138: Error: no such instruction: ld1 {v16.2d},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:138: Error: no such instruction:ld1 {v17.2d},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:138: Error: no such instruction: ld1 {v18.2d},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:138: Error: no such instruction:ld1 {v19.2d},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:140: Error: no such instruction: st1 {v16.2d},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:140: Error: no such instruction:st1 {v17.2d},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:140: Error: no such instruction: st1 {v18.2d},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:140: Error: no such instruction:st1 {v19.2d},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:146: Error: no such instruction: sxtw x1,w1'
  codec/common/arm64/copy_mb_aarch64_neon.S:147: Error: no such instruction:sxtw x3,w3' codec/common/arm64/copy_mb_aarch64_neon.S:148: Error: no such instruction: ld1 {v0.16b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:148: Error: no such instruction:ld1 {v1.16b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:148: Error: no such instruction: ld1 {v2.16b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:148: Error: no such instruction:ld1 {v3.16b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:150: Error: no such instruction: st1 {v0.16b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:150: Error: no such instruction:st1 {v1.16b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:150: Error: no such instruction: st1 {v2.16b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:150: Error: no such instruction:st1 {v3.16b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:152: Error: no such instruction: ld1 {v16.16b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:152: Error: no such instruction:ld1 {v17.16b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:152: Error: no such instruction: ld1 {v18.16b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:152: Error: no such instruction:ld1 {v19.16b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:154: Error: no such instruction: st1 {v16.16b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:154: Error: no such instruction:st1 {v17.16b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:154: Error: no such instruction: st1 {v18.16b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:154: Error: no such instruction:st1 {v19.16b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:156: Error: no such instruction: ld1 {v0.16b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:156: Error: no such instruction:ld1 {v1.16b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:156: Error: no such instruction: ld1 {v2.16b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:156: Error: no such instruction:ld1 {v3.16b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:158: Error: no such instruction: st1 {v0.16b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:158: Error: no such instruction:st1 {v1.16b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:158: Error: no such instruction: st1 {v2.16b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:158: Error: no such instruction:st1 {v3.16b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:160: Error: no such instruction: ld1 {v16.16b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:160: Error: no such instruction:ld1 {v17.16b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:160: Error: no such instruction: ld1 {v18.16b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:160: Error: no such instruction:ld1 {v19.16b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:162: Error: no such instruction: st1 {v16.16b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:162: Error: no such instruction:st1 {v17.16b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:162: Error: no such instruction: st1 {v18.16b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:162: Error: no such instruction:st1 {v19.16b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:168: Error: no such instruction: sxtw x1,w1'
  codec/common/arm64/copy_mb_aarch64_neon.S:169: Error: no such instruction:sxtw x3,w3' codec/common/arm64/copy_mb_aarch64_neon.S:170: Error: no such instruction: ld1 {v0.16b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:170: Error: no such instruction:ld1 {v1.16b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:170: Error: no such instruction: ld1 {v2.16b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:170: Error: no such instruction:ld1 {v3.16b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:172: Error: no such instruction: st1 {v0.16b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:172: Error: no such instruction:st1 {v1.16b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:172: Error: no such instruction: st1 {v2.16b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:172: Error: no such instruction:st1 {v3.16b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:174: Error: no such instruction: ld1 {v16.16b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:174: Error: no such instruction:ld1 {v17.16b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:174: Error: no such instruction: ld1 {v18.16b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:174: Error: no such instruction:ld1 {v19.16b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:176: Error: no such instruction: st1 {v16.16b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:176: Error: no such instruction:st1 {v17.16b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:176: Error: no such instruction: st1 {v18.16b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:176: Error: no such instruction:st1 {v19.16b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:182: Error: no such instruction: sxtw x1,w1'
  codec/common/arm64/copy_mb_aarch64_neon.S:183: Error: no such instruction:sxtw x3,w3' codec/common/arm64/copy_mb_aarch64_neon.S:184: Error: no such instruction: ld1 {v0.8b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:184: Error: no such instruction:ld1 {v1.8b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:184: Error: no such instruction: ld1 {v2.8b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:184: Error: no such instruction:ld1 {v3.8b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:186: Error: no such instruction: st1 {v0.8b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:186: Error: no such instruction:st1 {v1.8b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:186: Error: no such instruction: st1 {v2.8b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:186: Error: no such instruction:st1 {v3.8b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:188: Error: no such instruction: ld1 {v4.8b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:188: Error: no such instruction:ld1 {v5.8b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:188: Error: no such instruction: ld1 {v6.8b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:188: Error: no such instruction:ld1 {v7.8b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:190: Error: no such instruction: st1 {v4.8b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:190: Error: no such instruction:st1 {v5.8b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:190: Error: no such instruction: st1 {v6.8b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:190: Error: no such instruction:st1 {v7.8b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:192: Error: no such instruction: ld1 {v0.8b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:192: Error: no such instruction:ld1 {v1.8b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:192: Error: no such instruction: ld1 {v2.8b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:192: Error: no such instruction:ld1 {v3.8b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:194: Error: no such instruction: st1 {v0.8b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:194: Error: no such instruction:st1 {v1.8b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:194: Error: no such instruction: st1 {v2.8b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:194: Error: no such instruction:st1 {v3.8b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:196: Error: no such instruction: ld1 {v4.8b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:196: Error: no such instruction:ld1 {v5.8b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:196: Error: no such instruction: ld1 {v6.8b},[x2],x3'
  codec/common/arm64/copy_mb_aarch64_neon.S:196: Error: no such instruction:ld1 {v7.8b},[x2],x3' codec/common/arm64/copy_mb_aarch64_neon.S:198: Error: no such instruction: st1 {v4.8b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:198: Error: no such instruction:st1 {v5.8b},[x0],x1' codec/common/arm64/copy_mb_aarch64_neon.S:198: Error: no such instruction: st1 {v6.8b},[x0],x1'
  codec/common/arm64/copy_mb_aarch64_neon.S:198: Error: no such instruction:st1 {v7.8b},[x0],x1' make: *** [codec/common/arm64/copy_mb_aarch64_neon.o] Error 1`

This is to build arm result:
`ikaros@ikaros-Virtual-Machine:~/openh264/v1.6/openh264$ make os=android NDKROOT=~/ndk/android-ndk-r14b/ TARGET=android-12 ARCH=arm NDKLEVEL=21 g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/common_tables.o codec/common/src/common_tables.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/copy_mb.o codec/common/src/copy_mb.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/cpu.o codec/common/src/cpu.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/crt_util_safe_x.o codec/common/src/crt_util_safe_x.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/deblocking_common.o codec/common/src/deblocking_common.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/expand_pic.o codec/common/src/expand_pic.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/intra_pred_common.o codec/common/src/intra_pred_common.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/mc.o codec/common/src/mc.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/memory_align.o codec/common/src/memory_align.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/sad_common.o codec/common/src/sad_common.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/utils.o codec/common/src/utils.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/welsCodecTrace.o codec/common/src/welsCodecTrace.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/WelsTaskThread.o codec/common/src/WelsTaskThread.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/WelsThread.o codec/common/src/WelsThread.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/WelsThreadLib.o codec/common/src/WelsThreadLib.cpp g++ -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/src/WelsThreadPool.o codec/common/src/WelsThreadPool.cpp cc -O3 -DNDEBUG -DHAVE_NEON -Wall -fno-strict-aliasing -fPIC -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/common/arm/ -march=armv7-a -mfpu=neon -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -c -o codec/common/arm/copy_mb_neon.o codec/common/arm/copy_mb_neon.S cc: error: unrecognized command line option ‘-mfpu=neon’ make: *** [codec/common/arm/copy_mb_neon.o] Error 1`

How can I do?

**Comment by Kao953** [comment] 2017-06-06 05:41
Ubuntu 14 is 32-bit.
I have just tried to use Ubuntu 14 64bit to build openh264 but the same results.

**Comment by GuangweiWang** [comment] 2017-06-06 06:38
ok.
Please use "OS=android" instead "os=android" on command line to specify the platform. the error from your build log caused by using x86 platform tools to build arm code.

**Comment by Kao953** [comment] 2017-06-06 07:16
To GuangweiWang
You are right,Thanks :)

**Comment by GuangweiWang** [comment] 2017-06-06 07:22
welcome~ 
if no update, will close this issue. thanks.

**Closed** 2017-06-06 07:25 UTC
