### ISSUE TITLE
Pixelated video (macroblocking) in the poor network

### ISSUE THREAD

**Issue by raycad** [cisco/openh264#1998] opened 2015-06-19 09:15 UTC
Hi there,
I have a problem of video call in the poor network. The frames are pixelated when showing movement frames. If P frame is enabled the macroblocking is always happen until it receives a static I frame. If using I frame only, the problem still happens but it is less worse than first one. The packets in stream is big since I send VGA with 25-30fps. Could you tell me the way to avoid this? Thanks in advance!

Got some error logs:
[OpenH264] this = 0x0x7f76c00a2660, Warning:bEnableFrameSkip = 0,bitrate can't be controlled for RC_QUALITY_MODE,RC_BITRATE_MODE and RC_TIMESTAMP_MODE without enabling skip frame.
[OpenH264] this = 0x0x7f76c00a2660, Warning:bEnableFrameSkip = 0,bitrate can't be controlled for RC_QUALITY_MODE,RC_BITRATE_MODE and RC_TIMESTAMP_MODE without enabling skip frame.
[OpenH264] this = 0x0x7f76c00210a0, Error:invalid syntax first_mb_in_slice 190
[OpenH264] this = 0x0x7f76c00210a0, Error:invalid syntax first_mb_in_slice 133
[OpenH264] this = 0x0x7f76c00210a0, Warning:DecodeCurrentAccessUnit() failed (1050) in frame: 9 uiDId: 0 uiQId: 0
[OpenH264] this = 0x0x7f76c00210a0, Warning:DecodeCurrentAccessUnit() failed (10012) in frame: 10 uiDId: 0 uiQId: 0
[OpenH264] this = 0x0x7f76c00210a0, Warning:invalid syntax vertical mv -1728
decode failed with state dsBitstreamError

My encode/decode initiation:
oh264_data->enc->GetDefaultParams(&eprm);
eprm.uiIntraPeriod = 8;
eprm.iTemporalLayerNum = 1;
eprm.iSpatialLayerNum = 1;

eprm.iUsageType = CAMERA_VIDEO_REAL_TIME;
eprm.iPicWidth = 640;
eprm.iPicHeight = 480;
eprm.iRCMode = RC_TIMESTAMP_MODE;
eprm.iTargetBitrate = 512000;
eprm.fMaxFrameRate = 25;
eprm.uiMaxNalSize = 1500;
eprm.bEnableFrameSkip = false; // frame skipping
eprm.bEnableDenoise = false; // denoise control
eprm.bEnableBackgroundDetection = false; // background detection control
eprm.bEnableAdaptiveQuant = 0; // adaptive quantization control
eprm.bEnableLongTermReference = false;
eprm.iLTRRefNum = 0;
eprm.iLtrMarkPeriod = 30;
eprm.bIsLosslessLink = false;
//eprm.bPrefixNalAddingCtrl = false;
eprm.bEnableSSEI = false;
eprm.bSimulcastAVC = false;
eprm.iNumRefFrame = AUTO_REF_PIC_COUNT;
eprm.iMultipleThreadIdc = 0;

SliceModeEnum sliceMode = (oh264_data->whole ? SM_SINGLE_SLICE : SM_DYN_SLICE);
// Intialize 4 spatial layer with differrent bitrate (same res)
for (int i = 0; i < eprm.iSpatialLayerNum; i++) {
if (i == 0)
eprm.sSpatialLayers[i].uiProfileIdc = PRO_BASELINE;
else
eprm.sSpatialLayers[i].uiProfileIdc = PRO_SCALABLE_BASELINE;
eprm.sSpatialLayers[i].uiLevelIdc = LEVEL_3_1;
eprm.sSpatialLayers[i].iVideoWidth = eprm.iPicWidth;
eprm.sSpatialLayers[i].iVideoHeight = eprm.iPicHeight;
eprm.sSpatialLayers[i].iSpatialBitrate = eprm.iTargetBitrate;
eprm.sSpatialLayers[1].iMaxSpatialBitrate = eprm.iMaxBitrate;
eprm.sSpatialLayers[i].fFrameRate = eprm.fMaxFrameRate;
eprm.sSpatialLayers[i].sSliceCfg.uiSliceMode = sliceMode;
if (eprm.sSpatialLayers[i].sSliceCfg.uiSliceMode == SM_DYN_SLICE) {
eprm.sSpatialLayers[i].sSliceCfg.sSliceArgument.uiSliceSizeConstraint = param->enc_mtu;
eprm.uiMaxNalSize = param->enc_mtu;
}
}

**Comment by sijchen** [comment] 2015-06-29 02:08
Hi, how is the "EncoderStatistic" logs? (INFO level log)
when you are using RC_TIMESTAMP_MODE, please make sure that the timestamp with the input frame (SrcPic) is in unite of milliseconds.

**Comment by raycad** [comment] 2015-06-30 04:56
Hi SijChen,
Thank you very much for the reply. I got pixelated problem when decoding frames. Here are the info logs of the decode function:
[OpenH264] this = 0x0x7faa980a08f0, Warning:ParamValidationExt(), slice mode = SM_DYN_SLICE, uiSliceSizeConstraint = 1368 ,uiMaxNalsize = 1368, will take uiMaxNalsize!
[OpenH264] this = 0x0x7faa9801e730, Info:CWelsDecoder::init_decoder(), openh264 codec version = 
[OpenH264] this = 0x0x7faa9801e730, Info:eVideoType: 1
[OpenH264] this = 0x0x7faa9801e730, Info:WelsRequestMem(): memory alloc size = 320 * 192, ref list size = 3
[OpenH264] this = 0x0x7faa9801e730, Info:SyncPictureResolutionExt(), overall memory usage: 4528116 bytes
[OpenH264] this = 0x0x7faa9801e730, Info:DecodeFrameConstruction(): will output first frame of new sequence, 320 x 192, crop_left:0, crop_right:0, crop_top:0, crop_bottom:6, ignored error packet:0.
[OpenH264] this = 0x0x7faa9801e730, Info:WelsRequestMem(): memory re-alloc for resolution change, size change from 320 * 192 to 640 * 368, ref list size change from 3 to 3
[OpenH264] this = 0x0x7faa9801e730, Info:SyncPictureResolutionExt(), overall memory usage: 6190719 bytes
[OpenH264] this = 0x0x7faa9801e730, Info:DecodeFrameConstruction(): will output first frame of new sequence, 640 x 368, crop_left:0, crop_right:0, crop_top:0, crop_bottom:4, ignored error packet:0.
[OpenH264] this = 0x0x7faa9801e730, Info:decode failed, failure type:4 

[OpenH264] this = 0x0x7faa9801e730, Info:SyncPictureResolutionExt(), overall memory usage: 6191399 bytes
[OpenH264] this = 0x0x7faa9801e730, Info:DecodeFrameConstruction(): will output first frame of new sequence, 640 x 368, crop_left:0, crop_right:0, crop_top:0, crop_bottom:4, ignored error packet:3.
[OpenH264] this = 0x0x7faa9801e730, Info:decode failed, failure type:4 
[OpenH264] this = 0x0x7faa9801e730, Info:SyncPictureResolutionExt(), overall memory usage: 6191399 bytes
[OpenH264] this = 0x0x7faa9801e730, Info:DecodeFrameConstruction(): will output first frame of new sequence, 640 x 368, crop_left:0, crop_right:0, crop_top:0, crop_bottom:4, ignored error packet:1.
[OpenH264] this = 0x0x7faa9801e730, Info:decode failed, failure type:4 

[OpenH264] this = 0x0x7faa9801e730, Info:SyncPictureResolutionExt(), overall memory usage: 6191399 bytes
[OpenH264] this = 0x0x7faa9801e730, Info:DecodeFrameConstruction(): will output first frame of new sequence, 640 x 368, crop_left:0, crop_right:0, crop_top:0, crop_bottom:4, ignored error packet:1.
[OpenH264] this = 0x0x7faa9801e730, Info:decode failed, failure type:4 
[OpenH264] this = 0x0x7faa9801e730, Info:SyncPictureResolutionExt(), overall memory usage: 6191399 bytes
[OpenH264] this = 0x0x7faa9801e730, Info:DecodeFrameConstruction(): will output first frame of new sequence, 640 x 368, crop_left:0, crop_right:0, crop_top:0, crop_bottom:4, ignored error packet:2.
[OpenH264] this = 0x0x7faa9801e730, Info:decode failed, failure type:4 

[OpenH264] this = 0x0x7faa9801e730, Info:SyncPictureResolutionExt(), overall memory usage: 6191399 bytes
[OpenH264] this = 0x0x7faa9801e730, Info:DecodeFrameConstruction(): will output first frame of new sequence, 640 x 368, crop_left:0, crop_right:0, crop_top:0, crop_bottom:4, ignored error packet:1.
[OpenH264] this = 0x0x7faa9801e730, Info:decode failed, failure type:4 
[OpenH264] this = 0x0x7faa9801e730, Info:SyncPictureResolutionExt(), overall memory usage: 6191399 bytes
[OpenH264] this = 0x0x7faa9801e730, Info:DecodeFrameConstruction(): will output first frame of new sequence, 640 x 368, crop_left:0, crop_right:0, crop_top:0, crop_bottom:4, ignored error packet:3.
[OpenH264] this = 0x0x7faa9801e730, Info:decode failed, failure type:4 

[OpenH264] this = 0x0x7faa9801e730, Info:SyncPictureResolutionExt(), overall memory usage: 6191399 bytes
[OpenH264] this = 0x0x7faa9801e730, Info:DecodeFrameConstruction(): will output first frame of new sequence, 640 x 368, crop_left:0, crop_right:0, crop_top:0, crop_bottom:4, ignored error packet:0.
[OpenH264] this = 0x0x7faa9801e730, Info:decode failed, failure type:4 

[OpenH264] this = 0x0x7faa9801e730, Info:SyncPictureResolutionExt(), overall memory usage: 6191399 bytes
[OpenH264] this = 0x0x7faa9801e730, Info:DecodeFrameConstruction(): will output first frame of new sequence, 640 x 368, crop_left:0, crop_right:0, crop_top:0, crop_bottom:4, ignored error packet:1.
[OpenH264] this = 0x0x7faa9801e730, Info:decode failed, failure type:4 
[OpenH264] this = 0x0x7faa9801e730, Info:SyncPictureResolutionExt(), overall memory usage: 6191399 bytes
[OpenH264] this = 0x0x7faa9801e730, Info:DecodeFrameConstruction(): will output first frame of new sequence, 640 x 368, crop_left:0, crop_right:0, crop_top:0, crop_bottom:4, ignored error packet:7.
[OpenH264] this = 0x0x7faa9801e730, Info:SyncPictureResolutionExt(), overall memory usage: 6191399 bytes
[OpenH264] this = 0x0x7faa9801e730, Info:DecodeFrameConstruction(): will output first frame of new sequence, 640 x 368, crop_left:0, crop_right:0, crop_top:0, crop_bottom:4, ignored error packet:0.
[OpenH264] this = 0x0x7faa9801e730, Info:decode failed, failure type:4

**Comment by sijchen** [comment] 2015-06-30 05:39
Hi do you mean the bitstream from encoder does not have the mentioned problem? If so, how is the setting of DECODER_OPTION_ERROR_CON_IDC?

**Comment by raycad** [comment] 2015-06-30 06:01
Yep. The test is a video call between 2 endpoints while the caller uses openh264 and the callee is Microsoft Lync endpoint. The callee (Lync) displays video well but the caller gets pixelated problem. Here is the decoder initiation:
ISVCDecoder	*dec;
int rc = WelsCreateDecoder(&dec);
if (rc) 
    return false;

SDecodingParam sDecParam = {0};
int traceLevel = WELS_LOG_INFO;
dec->SetOption(DECODER_OPTION_TRACE_LEVEL, &traceLevel);
sDecParam.sVideoProperty.size = sizeof(sDecParam.sVideoProperty);
sDecParam.eOutputColorFormat = videoFormatI420;
sDecParam.uiTargetDqLayer = (typedef unsigned char) - 1;
sDecParam.sVideoProperty.eVideoBsType = VIDEO_BITSTREAM_DEFAULT;

rc = dec->Initialize (&sDecParam);
if (rc) 
    return false;

int colorFmt = videoFormatI420;
rc = dec->SetOption(DECODER_OPTION_DATAFORMAT, &colorFmt);
if (rc) 
    return false;

**Comment by sijchen** [comment] 2015-06-30 06:15
is it able to find some logs related to "error_con" in the decoder side log?

**Comment by raycad** [comment] 2015-06-30 07:09
No, I don't see anything related to "error_con" in the log. All logs traced from openh264 are above.

**Comment by raycad** [comment] 2015-07-03 04:09
Has the latest commit supported SVC yet?

**Comment by sijchen** [comment] 2015-07-07 05:15
no we did not claim the support of H264 SVC.

**Comment by yingwang** [comment] 2015-07-07 14:16
Looks like caused by packet loss in the network. You can try different error concealment options using eEcActiveIdc in decoder parameter. For instance, ERROR_CON_DISABLE will turn off the decoder error concealment. You may also implement packet retransmission in your application.

**Comment by raycad** [comment] 2015-07-23 10:09
Thank you very much. 
I tried to set eEcActiveIdc to ERROR_CON_DISABLE already but the error still happens.
For packet retransmission, I'm intending to request the encoder to send I frame when detecting a frame lost by using encoder->ForceIntraFrame (true). Is this correct? and is it possible to send both I & P frames after that? (since I configured to use both I & P frames before).
Btw, do you know the best tool to able to detect packet loss in network?

**Comment by sijchen** [comment] 2015-08-27 05:28
ForceIntraFrame makes the next frame to be encoded to be IDR. Not quite sure what the last question is.

**Comment by sijchen** [comment] 2015-10-08 19:08
close this because of lack of updates from the asker.

**Closed by sijchen** 2015-10-08 19:08 UTC
