### ISSUE TITLE
x264 encoding + openh264 decoding = decoding bitstream errors?

### ISSUE THREAD

**Issue by dapirian** [cisco/openh264#2165] opened 2015-10-16 15:27 UTC
I'm using wirecast to encode a screen capture via x264 (@ 480p, 30fps, keyframes every 1 second, baseline profile). I have an application which decodes using openh264. About every 2-10 seconds I get about 10-30 frames of chain decoding errors every frame. It usually starts with a bitstream error.

x264 has many encoding options. I'm assuming it is encoding in a way openh264 doesn't support, but perhaps there is an option I can turn off to make openh264 decode properly. Does anyone have a clue as to what I should attempt to disable in order to have openh264 decode without errors?

Here's the error I get:

```
[OpenH264] this = 0x0x7fb7d9736ac0, Warning:invalid syntax vertical mv 23913
[OpenH264] this = 0x0x7fb7d9736ac0, Warning:DecodeCurrentAccessUnit() failed (1035) in frame: 3 uiDId: 0 uiQId: 0
[OpenH264] this = 0x0x7fb7d9736ac0, Info:decode failed, failure type:36 
```

Note: when I turn on error concealment it does an okay job at concealing this problem, but I still get visual artifacts, depending on the data, every 30s or so.

**Comment by sijchen** [comment] 2015-10-16 17:43
could you also give the options you use with x264, or give us the bit stream so that we can check?

**Comment by dapirian** [comment] 2015-10-16 17:51
wirecast hides the exact options... I am able to add options though. Here's what I can select...

![screen shot 2015-10-16 at 10 50 41 am](https://cloud.githubusercontent.com/assets/3904462/10549088/c7769e7a-73f3-11e5-8d4a-e999969d6466.png)

**Comment by sijchen** [comment] 2015-10-16 17:55
oops, why I see in email the following png:
https://cloud.githubusercontent.com/assets/3904462/10549088/c7769e7a-73f3-11e5-8d4a-e999969d6466.png

**Comment by dapirian** [comment] 2015-10-16 17:58
@sijchen I accidentally uploaded the wrong screenshot first, and then corrected it

**Comment by sijchen** [comment] 2015-10-16 18:00
the baseline setting seems no problem, however, my guess is openh264 is support Constrained Baseline which does not include FMO which is included by Baseline profile, which may make the difference. The best way to confirm this, is to get the bit stream you fed to openh264 decoder which makes the above error message. Thanks.

**Comment by dapirian** [comment] 2015-10-16 18:41
@sijchen See attachment that I put as a png, but it really is a bitstream. It wouldn't let me upload anything except an image format.

![output](https://cloud.githubusercontent.com/assets/3904462/10550254/ca8222b8-73fa-11e5-9b85-fc842c3e6d7d.png)

**Comment by dapirian** [comment] 2015-10-16 18:56
@sijchen Another note, I'm typically getting this error from DecodeFrame2 now:

     [OpenH264] this = 0x0x7ff4c156ff50, Warning:DecodeCurrentAccessUnit() failed (-1) in frame: 0 uiDId: 0 uiQId: 0
     [OpenH264] this = 0x0x7ff4c156ff50, Info:DecodeFrameConstruction(): will output first frame of new sequence, 1280 x 720, crop_left:0, crop_right:0, crop_top:0, crop_bottom:0, ignored error packet:0.
     [OpenH264] this = 0x0x7ff4c156ff50, Info:decode failed, failure type:36 

Followed by ~20 frames of error 32, and then it recovers again.

**Comment by sijchen** [comment] 2015-10-16 19:06
it seems that the file you uploaded is not started with an IDR frame.

the error 36 indicates that the IDR frames is not decoded correctly with some error in bit stream syntax, and the frame is reconstructed with error-concealment. Then afterwards all the P frames will be with error-concealment and with the error code32.

**Comment by dapirian** [comment] 2015-10-16 19:11
@sijchen This comes from a stream which has IDR frames every second. When it initially starts I may not have an IDR frame yet, but within a second that is resolved. As it continues, after an IDR frame has come through, these errors continue happening. Near the end of the bitstream I uploaded I get the same kind of errors, after an IDR frame has come.

**Comment by huili2** [comment] 2015-10-19 03:14
@dapirian the bitstream contains illegal NAL data in several pictures including the first "decodable" IDR picture. Our decoder handle this as bitstream error.

In detail, in the Rec it is defined for emulation_prevention_three_byte(7.4.1):
Within the NAL unit, any four-byte sequence that starts with 0x000003 other than the following sequences shall not occur at any byte-aligned position:
– 0x00000300
– 0x00000301
– 0x00000302
– 0x00000303

However, in the given bitstream, it contains several like "0x00000380" "0x00000313“ "0x0000038D", etc.

**Comment by dapirian** [comment] 2015-10-19 16:47
@huili2 I see. That was definitely a problem, but I fixed it and the exact same thing is happening. I've tried to save the minimal bitstream that can cause the problem (I have 2 examples):

![output](https://cloud.githubusercontent.com/assets/3904462/10584309/5fab0e34-7646-11e5-85b4-e901e23c14e2.png)
![output1](https://cloud.githubusercontent.com/assets/3904462/10584308/5fa77fda-7646-11e5-8921-0c4671d7b7af.png)

**Comment by huili2** [comment] 2015-10-20 01:10
@dapirian sorry cannot correctly decode the data you provided either 1 (no SPS/PPS) or 2 (no IDR). Could you please provide similar data as in the first case?

**Comment by dapirian** [comment] 2015-10-20 17:13
@sijchen Sure:

![output](https://cloud.githubusercontent.com/assets/3904462/10615162/0c6cb9b6-7713-11e5-9145-37560d776a9e.png)

Again, it doesn't start with an IDR frame, because I'm connecting mid stream. But those errors are okay with me. After an IDR frame comes there are more of the same errors I described above.

**Comment by huili2** [comment] 2015-10-21 00:59
@dapirian this bitstream has available head info. 
From my test, just very few "DecodeCurrentAccessUnit() failed" occurs at latter part from our openh264 decoder, and the content is always acceptable. Could you please try this bitstream again?

**Comment by leochan2009** [comment] 2016-08-02 16:35
Hi, I have similar problem, i use X264 as encoder and set the profile as baseline,  openH264 as decoder.  Any update on this thread?
Thanks

**Comment by huili2** [comment] 2016-08-03 00:58
@leochan20009, above issue is caused by incomplete bitstream provided. Could you please give us the spec bitstream for tuning for your case?

**Comment by leochan2009** [comment] 2016-08-03 18:49
@huili2  Thanks for your prompt reply, my develop environment includes data transmission over the wifi,  i will check if the bit stream is correctly transmitted and come to you again.
many thanks again!

Best,
Longquan

**Comment by leochan2009** [comment] 2016-08-11 15:22
@huili2 
I made some bitstream, it would be nice if you could take a look into it.
Here is a quick screen shot of the bit stream. you could see at the beginning of the stream there are 2/3 nal units about the copy right of the X264. 
<img width="1557" alt="screen shot 2016-08-11 at 11 17 51 am" src="https://cloud.githubusercontent.com/assets/10211992/17594045/d74b8ece-5fb5-11e6-80bc-4b5e759a8e35.png">

The bit stream file i could send to you via email
Thanks in advance 
Best Regards,
Longquan

**Comment by leochan2009** [comment] 2016-08-11 15:30
@huili2 
Could you give me your email address, so that i could send you the binary file 
It seems that i could not paste the file directly in Github:-(

Best,
Longquan

**Comment by huili2** [comment] 2016-08-12 06:50
huili2@cisco.com please.

**Comment by huili2** [comment] 2016-11-23 01:35
already discussed in mail long time ago. Since no progress again, close it.

**Closed by huili2** 2016-11-23 01:35 UTC
Labels: answered
