### ISSUE TITLE
Deocoder issue when change encoder setting

### ISSUE THREAD

**Issue by kotakakaji** [cisco/openh264#1898] opened 2015-04-17 02:36 UTC
I'm currently deal with this problem when change setting (resolution and mode) of encoder. 

Encoder start with res 640 x 480, after that, I change stream from camera to desktop sharing mode, and res change to 1280 x 720. I have destroyed encoder and reinitialize with new setting (SCREEN_CONTENT_REAL_TIME and new resolution). Decoder, on the remote peer still unchange.

Decoder decode well, but some time this occur:
- Original image:
![orginal](https://cloud.githubusercontent.com/assets/6323261/7195135/eab85232-e4e4-11e4-9271-10e865887a44.jpg)

- Decode image:
![capture](https://cloud.githubusercontent.com/assets/6323261/7195138/ef30e2ac-e4e4-11e4-8eec-c06b7ae837f3.jpg)

Some time this occur, and some time run well. In both case, decoder does not show any error.
How can i solve this?

**Comment by huili2** [comment] 2015-04-17 05:42
seems not  the decoder issue. Can you make sure the encoding setting is correct?

**Comment by kotakakaji** [comment] 2015-04-17 05:53
Hi huili2,
This is configuration of encoder when in camera capture:
	params.iUsageType = CAMERA_VIDEO_REAL_TIME;
	params.iPicWidth = 640;
	params.iPicHeight = 480;
	params.iRCMode = RC_BITRATE_MODE;
	params.iTargetBitrate = _bitrate * 1000;
	params.iMaxBitrate = _bitrate  * 1000;
	params.uiMaxNalSize = 1500;
	params.bEnableFrameSkip = false; // frame skipping
	params.bEnableDenoise = false; // denoise control
	params.bEnableBackgroundDetection = false; // background detection control
	params.bEnableAdaptiveQuant = 0; // adaptive quantization control
	params.bEnableLongTermReference = false;
	params.iLTRRefNum = 0;
	params.iLtrMarkPeriod = 0;
	params.bIsLosslessLink = false;
	params.iSpatialLayerNum = 4;

	// Intialize 4 spatial layer with differrent bitrate (same res)
	for (int i = 0; i < params.iSpatialLayerNum; i++) {
		if (i == 0)
			params.sSpatialLayers[i].uiProfileIdc = PRO_BASELINE;
		else
			params.sSpatialLayers[i].uiProfileIdc = PRO_SCALABLE_BASELINE;
		params.sSpatialLayers[i].iVideoWidth = 640;
		params.sSpatialLayers[i].iVideoHeight = 480;
		params.sSpatialLayers[i].iSpatialBitrate = _spatialLayers[i].bitrate * 1000;
		params.sSpatialLayers[i].fFrameRate = 30;
		params.sSpatialLayers[i].sSliceCfg.uiSliceMode = SLICE_MODE;
		if (params.sSpatialLayers[i].sSliceCfg.uiSliceMode == SM_DYN_SLICE) {
			params.sSpatialLayers[i].sSliceCfg.sSliceArgument.uiSliceSizeConstraint = SLICE_SIZE_CONSTRAINT;
			params.uiMaxNalSize = 1500;
		}
	}

After switch to scren capture mode, I destroy video encoder and reinitialize with this setting (encoder with 1 layer):
	
	SEncParamBase paramsBase;
	memset(&paramsBase, 0, sizeof (SEncParamBase));
	paramsBase.iUsageType = SCREEN_CONTENT_REAL_TIME;
	paramsBase.fMaxFrameRate = 15;
	paramsBase.iPicWidth = 1280;
	paramsBase.iPicHeight = 720;
	paramsBase.iTargetBitrate=500000;

**Comment by huili2** [comment] 2015-04-17 06:35
Cannot directly find the root cause. But could you please set the spatial layer num to be 1, if it would not cause other issues? Current decoder is unable to decode several layers input.

**Comment by sijchen** [comment] 2015-10-08 19:02
close this because of answered and no further update afterwards.

**Closed by sijchen** 2015-10-08 19:02 UTC
