### ISSUE TITLE
Building on windows with MinGW seems broken...

### ISSUE THREAD

**Issue by XeonG** [cisco/openh264#2455] opened 2016-05-06 09:33 UTC
F:\openh264-master>make
g++ -O3 -DNDEBUG -m32 -DX86_ASM -DX86_32_ASM -MMD -MP -DGENERATED_VERSION_HEADER
  -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -o codec/common
/src/cpu.o codec/common/src/cpu.cpp
C:\Users\blah\AppData\Local\Temp\ccSpIEkj.s: Assembler messages:
C:\Users\blah\AppData\Local\Temp\ccSpIEkj.s:384: Error: expecting string instr
uction after `rep'
make: **\* [codec/common/src/cpu.o] Error 1

Win7 x64

Also why not update the compiled releases(still at 1.5) for all platforms again, the last update was last year :S 

AutoBuildForWPAndWindows.bat.....

Also ing/src/arm/down_sample_neon.obj codec/processing/src/arm/pixel_sad_neon.obj cod
ec/processing/src/arm/vaa_calc_neon.obj common.lib decoder.lib encoder.lib proce
ssing.lib openh264.lib openh264.dll  _.lib *.a *.dylib *.dll *.so *.exe *.pdb *.
exp *.pc *.res *.map
cl -Od -Oy- -Zi -RTC1 -D_DEBUG -MDd -DHAVE_NEON -nologo -W3 -EHsc -fp:precise -Z
c:wchar_t -Zc:forScope -D_VARIADIC_MAX=10 -DUNICODE -DWINAPI_FAMILY=WINAPI_FAMIL
Y_PHONE_APP -DWINDOWS_PHONE -DGENERATED_VERSION_HEADER -ZW -wd4447 -I./codec/api
/svc -I./codec/common/inc -Icodec/common/inc   -c -Focodec/common/src/common_tab
les.obj codec/common/src/common_tables.cpp
common_tables.cpp
codec/common/src/common_tables.cpp: fatal error C1107: could not find assembly '
platform.winmd': please specify the assembly search path using /AI or by setting
 the LIBPATH environment variable
make: *_\* [codec/common/src/common_tables.obj] Error 2
copying dll files to destination folder...
FullDestDir is F:\openh264-master\bin\ARM\Debug
current dir is:
F:\openh264-master
DestDir is bin/ARM/Debug
cp: cannot stat `openh264.dll': No such file or directory
cp: cannot stat`openh264.lib': No such file or directory
cp: cannot stat `openh264.pdb': No such file or directory
cp: cannot stat`ut.dll': No such file or directory
bash -c "make OS=msvc-wp  ARCH=arm USE_ASM=Yes BUILDTYPE=Release clean"
bash -c "make OS=msvc-wp  ARCH=arm USE_ASM=Yes BUILDTYPE=Release"
rm -f codec/common/x86/cpuid.obj codec/common/x86/dct.obj codec/common/x86/deblo
ck.obj codec/common/x86/expand_picture.obj codec/common/x86/intra_pred_com.obj c
odec/common/x86/mb_copy.obj codec/common/x86/mc_chroma.obj codec/common/x86/mc_l
uma.obj codec/common/x86/satd_sad.obj codec/common/x86/vaa.obj codec/common/arm/
copy_mb_neon.obj codec/common/arm/deblocking_neon.obj codec/common/arm/expand_pi
cture_neon.obj codec/common/arm/intra_pred_common_neon.obj codec/common/arm/mc_n
eon.obj codec/common/arm64/copy_mb_aarch64_neon.obj codec/common/arm64/deblockin
g_aarch64_neon.obj codec/common/arm64/expand_picture_aarch64_neon.obj codec/comm
on/arm64/intra_pred_common_aarch64_neon.obj codec/common/arm64/mc_aarch64_neon.o
bj codec/common/src/common_tables.obj codec/common/src/copy_mb.obj codec/common/
src/cpu.obj codec/common/src/crt_util_safe_x.obj codec/common/src/deblocking_com
mon.obj codec/common/src/expand_pic.obj codec/common/src/intra_pred_common.obj c
odec/common/src/mc.obj codec/common/src/memory_align.obj codec/common/src/sad_co
mmon.obj codec/common/src/utils.obj codec/common/src/welsCodecTrace.obj codec/co
mmon/src/WelsTaskThread.obj codec/common/src/WelsThread.obj codec/common/src/Wel
sThreadLib.obj codec/common/src/WelsThreadPool.obj codec/common/arm/copy_mb_neon
.obj codec/common/arm/deblocking_neon.obj codec/common/arm/expand_picture_neon.o
bj codec/common/arm/intra_pred_common_neon.obj codec/common/arm/mc_neon.obj code
c/decoder/core/x86/dct.obj codec/decoder/core/x86/intra_pred.obj codec/decoder/c
ore/arm/block_add_neon.obj codec/decoder/core/arm/intra_pred_neon.obj codec/deco
der/core/arm64/block_add_aarch64_neon.obj codec/decoder/core/arm64/intra_pred_aa
rch64_neon.obj codec/decoder/core/src/au_parser.obj codec/decoder/core/src/bit_s
tream.obj codec/decoder/core/src/cabac_decoder.obj codec/decoder/core/src/debloc
king.obj codec/decoder/core/src/decode_mb_aux.obj codec/decoder/core/src/decode_
slice.obj codec/decoder/core/src/decoder.obj codec/decoder/core/src/decoder_core
.obj codec/decoder/core/src/decoder_data_tables.obj codec/decoder/core/src/error
_concealment.obj codec/decoder/core/src/fmo.obj codec/decoder/core/src/get_intra
_predictor.obj codec/decoder/core/src/manage_dec_ref.obj codec/decoder/core/src/
memmgr_nal_unit.obj codec/decoder/core/src/mv_pred.obj codec/decoder/core/src/pa
rse_mb_syn_cabac.obj codec/decoder/core/src/parse_mb_syn_cavlc.obj codec/decoder
/core/src/pic_queue.obj codec/decoder/core/src/rec_mb.obj codec/decoder/plus/src
/welsDecoderExt.obj codec/decoder/core/arm/block_add_neon.obj codec/decoder/core
/arm/intra_pred_neon.obj codec/encoder/core/x86/coeff.obj codec/encoder/core/x86
/dct.obj codec/encoder/core/x86/intra_pred.obj codec/encoder/core/x86/matrix_tra
nspose.obj codec/encoder/core/x86/memzero.obj codec/encoder/core/x86/quant.obj c
odec/encoder/core/x86/sample_sc.obj codec/encoder/core/x86/score.obj codec/encod
er/core/arm/intra_pred_neon.obj codec/encoder/core/arm/intra_pred_sad_3_opt_neon
.obj codec/encoder/core/arm/memory_neon.obj codec/encoder/core/arm/pixel_neon.ob
j codec/encoder/core/arm/reconstruct_neon.obj codec/encoder/core/arm/svc_motion_
estimation.obj codec/encoder/core/arm64/intra_pred_aarch64_neon.obj codec/encode
r/core/arm64/intra_pred_sad_3_opt_aarch64_neon.obj codec/encoder/core/arm64/memo
ry_aarch64_neon.obj codec/encoder/core/arm64/pixel_aarch64_neon.obj codec/encode
r/core/arm64/reconstruct_aarch64_neon.obj codec/encoder/core/arm64/svc_motion_es
timation_aarch64_neon.obj codec/encoder/core/src/au_set.obj codec/encoder/core/s
rc/deblocking.obj codec/encoder/core/src/decode_mb_aux.obj codec/encoder/core/sr
c/encode_mb_aux.obj codec/encoder/core/src/encoder.obj codec/encoder/core/src/en
coder_data_tables.obj codec/encoder/core/src/encoder_ext.obj codec/encoder/core/
src/get_intra_predictor.obj codec/encoder/core/src/md.obj codec/encoder/core/src
/mv_pred.obj codec/encoder/core/src/nal_encap.obj codec/encoder/core/src/picture
_handle.obj codec/encoder/core/src/ratectl.obj codec/encoder/core/src/ref_list_m
gr_svc.obj codec/encoder/core/src/sample.obj codec/encoder/core/src/set_mb_syn_c
abac.obj codec/encoder/core/src/set_mb_syn_cavlc.obj codec/encoder/core/src/slic
e_multi_threading.obj codec/encoder/core/src/svc_base_layer_md.obj codec/encoder
/core/src/svc_enc_slice_segment.obj codec/encoder/core/src/svc_encode_mb.obj cod
ec/encoder/core/src/svc_encode_slice.obj codec/encoder/core/src/svc_mode_decisio
n.obj codec/encoder/core/src/svc_motion_estimate.obj codec/encoder/core/src/svc_
set_mb_syn_cabac.obj codec/encoder/core/src/svc_set_mb_syn_cavlc.obj codec/encod
er/core/src/wels_preprocess.obj codec/encoder/core/src/wels_task_base.obj codec/
encoder/core/src/wels_task_encoder.obj codec/encoder/core/src/wels_task_manageme
nt.obj codec/encoder/plus/src/welsEncoderExt.obj codec/encoder/core/arm/intra_pr
ed_neon.obj codec/encoder/core/arm/intra_pred_sad_3_opt_neon.obj codec/encoder/c
ore/arm/memory_neon.obj codec/encoder/core/arm/pixel_neon.obj codec/encoder/core
/arm/reconstruct_neon.obj codec/encoder/core/arm/svc_motion_estimation.obj codec
/processing/src/x86/denoisefilter.obj codec/processing/src/x86/downsample_biline
ar.obj codec/processing/src/x86/vaa.obj codec/processing/src/arm/adaptive_quanti
zation.obj codec/processing/src/arm/down_sample_neon.obj codec/processing/src/ar
m/pixel_sad_neon.obj codec/processing/src/arm/vaa_calc_neon.obj codec/processing
/src/arm64/adaptive_quantization_aarch64_neon.obj codec/processing/src/arm64/dow
n_sample_aarch64_neon.obj codec/processing/src/arm64/pixel_sad_aarch64_neon.obj
codec/processing/src/arm64/vaa_calc_aarch64_neon.obj codec/processing/src/adapti
vequantization/AdaptiveQuantization.obj codec/processing/src/backgrounddetection
/BackgroundDetection.obj codec/processing/src/common/memory.obj codec/processing
/src/common/WelsFrameWork.obj codec/processing/src/common/WelsFrameWorkEx.obj co
dec/processing/src/complexityanalysis/ComplexityAnalysis.obj codec/processing/sr
c/denoise/denoise.obj codec/processing/src/denoise/denoise_filter.obj codec/proc
essing/src/downsample/downsample.obj codec/processing/src/downsample/downsamplef
uncs.obj codec/processing/src/imagerotate/imagerotate.obj codec/processing/src/i
magerotate/imagerotatefuncs.obj codec/processing/src/scenechangedetection/SceneC
hangeDetection.obj codec/processing/src/scrolldetection/ScrollDetection.obj code
c/processing/src/scrolldetection/ScrollDetectionFuncs.obj codec/processing/src/v
aacalc/vaacalcfuncs.obj codec/processing/src/vaacalc/vaacalculation.obj codec/pr
ocessing/src/arm/adaptive_quantization.obj codec/processing/src/arm/down_sample_
neon.obj codec/processing/src/arm/pixel_sad_neon.obj codec/processing/src/arm/va
a_calc_neon.obj codec/common/x86/cpuid.d codec/common/x86/dct.d codec/common/x86
/deblock.d codec/common/x86/expand_picture.d codec/common/x86/intra_pred_com.d c
odec/common/x86/mb_copy.d codec/common/x86/mc_chroma.d codec/common/x86/mc_luma.
d codec/common/x86/satd_sad.d codec/common/x86/vaa.d codec/common/arm/copy_mb_ne
on.d codec/common/arm/deblocking_neon.d codec/common/arm/expand_picture_neon.d c
odec/common/arm/intra_pred_common_neon.d codec/common/arm/mc_neon.d codec/common
/arm64/copy_mb_aarch64_neon.d codec/common/arm64/deblocking_aarch64_neon.d codec
/common/arm64/expand_picture_aarch64_neon.d codec/common/arm64/intra_pred_common
_aarch64_neon.d codec/common/arm64/mc_aarch64_neon.d codec/common/src/common_tab
les.d codec/common/src/copy_mb.d codec/common/src/cpu.d codec/common/src/crt_uti
l_safe_x.d codec/common/src/deblocking_common.d codec/common/src/expand_pic.d co
dec/common/src/intra_pred_common.d codec/common/src/mc.d codec/common/src/memory
_align.d codec/common/src/sad_common.d codec/common/src/utils.d codec/common/src
/welsCodecTrace.d codec/common/src/WelsTaskThread.d codec/common/src/WelsThread.
d codec/common/src/WelsThreadLib.d codec/common/src/WelsThreadPool.d codec/commo
n/arm/copy_mb_neon.d codec/common/arm/deblocking_neon.d codec/common/arm/expand_
picture_neon.d codec/common/arm/intra_pred_common_neon.d codec/common/arm/mc_neo
n.d codec/decoder/core/x86/dct.d codec/decoder/core/x86/intra_pred.d codec/decod
er/core/arm/block_add_neon.d codec/decoder/core/arm/intra_pred_neon.d codec/deco
der/core/arm64/block_add_aarch64_neon.d codec/decoder/core/arm64/intra_pred_aarc
h64_neon.d codec/decoder/core/src/au_parser.d codec/decoder/core/src/bit_stream.
d codec/decoder/core/src/cabac_decoder.d codec/decoder/core/src/deblocking.d cod
ec/decoder/core/src/decode_mb_aux.d codec/decoder/core/src/decode_slice.d codec/
decoder/core/src/decoder.d codec/decoder/core/src/decoder_core.d codec/decoder/c
ore/src/decoder_data_tables.d codec/decoder/core/src/error_concealment.d codec/d
ecoder/core/src/fmo.d codec/decoder/core/src/get_intra_predictor.d codec/decoder
/core/src/manage_dec_ref.d codec/decoder/core/src/memmgr_nal_unit.d codec/decode
r/core/src/mv_pred.d codec/decoder/core/src/parse_mb_syn_cabac.d codec/decoder/c
ore/src/parse_mb_syn_cavlc.d codec/decoder/core/src/pic_queue.d codec/decoder/co
re/src/rec_mb.d codec/decoder/plus/src/welsDecoderExt.d codec/decoder/core/arm/b
lock_add_neon.d codec/decoder/core/arm/intra_pred_neon.d codec/encoder/core/x86/
coeff.d codec/encoder/core/x86/dct.d codec/encoder/core/x86/intra_pred.d codec/e
ncoder/core/x86/matrix_transpose.d codec/encoder/core/x86/memzero.d codec/encode
r/core/x86/quant.d codec/encoder/core/x86/sample_sc.d codec/encoder/core/x86/sco
re.d codec/encoder/core/arm/intra_pred_neon.d codec/encoder/core/arm/intra_pred_
sad_3_opt_neon.d codec/encoder/core/arm/memory_neon.d codec/encoder/core/arm/pix
el_neon.d codec/encoder/core/arm/reconstruct_neon.d codec/encoder/core/arm/svc_m
otion_estimation.d codec/encoder/core/arm64/intra_pred_aarch64_neon.d codec/enco
der/core/arm64/intra_pred_sad_3_opt_aarch64_neon.d codec/encoder/core/arm64/memo
ry_aarch64_neon.d codec/encoder/core/arm64/pixel_aarch64_neon.d codec/encoder/co
re/arm64/reconstruct_aarch64_neon.d codec/encoder/core/arm64/svc_motion_estimati
on_aarch64_neon.d codec/encoder/core/src/au_set.d codec/encoder/core/src/deblock
ing.d codec/encoder/core/src/decode_mb_aux.d codec/encoder/core/src/encode_mb_au
x.d codec/encoder/core/src/encoder.d codec/encoder/core/src/encoder_data_tables.
d codec/encoder/core/src/encoder_ext.d codec/encoder/core/src/get_intra_predicto
r.d codec/encoder/core/src/md.d codec/encoder/core/src/mv_pred.d codec/encoder/c
ore/src/nal_encap.d codec/encoder/core/src/picture_handle.d codec/encoder/core/s
rc/ratectl.d codec/encoder/core/src/ref_list_mgr_svc.d codec/encoder/core/src/sa
mple.d codec/encoder/core/src/set_mb_syn_cabac.d codec/encoder/core/src/set_mb_s
yn_cavlc.d codec/encoder/core/src/slice_multi_threading.d codec/encoder/core/src
/svc_base_layer_md.d codec/encoder/core/src/svc_enc_slice_segment.d codec/encode
r/core/src/svc_encode_mb.d codec/encoder/core/src/svc_encode_slice.d codec/encod
er/core/src/svc_mode_decision.d codec/encoder/core/src/svc_motion_estimate.d cod
ec/encoder/core/src/svc_set_mb_syn_cabac.d codec/encoder/core/src/svc_set_mb_syn
_cavlc.d codec/encoder/core/src/wels_preprocess.d codec/encoder/core/src/wels_ta
sk_base.d codec/encoder/core/src/wels_task_encoder.d codec/encoder/core/src/wels
_task_management.d codec/encoder/plus/src/welsEncoderExt.d codec/encoder/core/ar
m/intra_pred_neon.d codec/encoder/core/arm/intra_pred_sad_3_opt_neon.d codec/enc
oder/core/arm/memory_neon.d codec/encoder/core/arm/pixel_neon.d codec/encoder/co
re/arm/reconstruct_neon.d codec/encoder/core/arm/svc_motion_estimation.d codec/p
rocessing/src/x86/denoisefilter.d codec/processing/src/x86/downsample_bilinear.d
 codec/processing/src/x86/vaa.d codec/processing/src/arm/adaptive_quantization.d
 codec/processing/src/arm/down_sample_neon.d codec/processing/src/arm/pixel_sad_
neon.d codec/processing/src/arm/vaa_calc_neon.d codec/processing/src/arm64/adapt
ive_quantization_aarch64_neon.d codec/processing/src/arm64/down_sample_aarch64_n
eon.d codec/processing/src/arm64/pixel_sad_aarch64_neon.d codec/processing/src/a
rm64/vaa_calc_aarch64_neon.d codec/processing/src/adaptivequantization/AdaptiveQ
uantization.d codec/processing/src/backgrounddetection/BackgroundDetection.d cod
ec/processing/src/common/memory.d codec/processing/src/common/WelsFrameWork.d co
dec/processing/src/common/WelsFrameWorkEx.d codec/processing/src/complexityanaly
sis/ComplexityAnalysis.d codec/processing/src/denoise/denoise.d codec/processing
/src/denoise/denoise_filter.d codec/processing/src/downsample/downsample.d codec
/processing/src/downsample/downsamplefuncs.d codec/processing/src/imagerotate/im
agerotate.d codec/processing/src/imagerotate/imagerotatefuncs.d codec/processing
/src/scenechangedetection/SceneChangeDetection.d codec/processing/src/scrolldete
ction/ScrollDetection.d codec/processing/src/scrolldetection/ScrollDetectionFunc
s.d codec/processing/src/vaacalc/vaacalcfuncs.d codec/processing/src/vaacalc/vaa
calculation.d codec/processing/src/arm/adaptive_quantization.d codec/processing/
src/arm/down_sample_neon.d codec/processing/src/arm/pixel_sad_neon.d codec/proce
ssing/src/arm/vaa_calc_neon.d codec/common/x86/cpuid.obj codec/common/x86/dct.ob
j codec/common/x86/deblock.obj codec/common/x86/expand_picture.obj codec/common/
x86/intra_pred_com.obj codec/common/x86/mb_copy.obj codec/common/x86/mc_chroma.o
bj codec/common/x86/mc_luma.obj codec/common/x86/satd_sad.obj codec/common/x86/v
aa.obj codec/common/arm/copy_mb_neon.obj codec/common/arm/deblocking_neon.obj co
dec/common/arm/expand_picture_neon.obj codec/common/arm/intra_pred_common_neon.o
bj codec/common/arm/mc_neon.obj codec/common/arm64/copy_mb_aarch64_neon.obj code
c/common/arm64/deblocking_aarch64_neon.obj codec/common/arm64/expand_picture_aar
ch64_neon.obj codec/common/arm64/intra_pred_common_aarch64_neon.obj codec/common
/arm64/mc_aarch64_neon.obj codec/common/src/common_tables.obj codec/common/src/c
opy_mb.obj codec/common/src/cpu.obj codec/common/src/crt_util_safe_x.obj codec/c
ommon/src/deblocking_common.obj codec/common/src/expand_pic.obj codec/common/src
/intra_pred_common.obj codec/common/src/mc.obj codec/common/src/memory_align.obj
 codec/common/src/sad_common.obj codec/common/src/utils.obj codec/common/src/wel
sCodecTrace.obj codec/common/src/WelsTaskThread.obj codec/common/src/WelsThread.
obj codec/common/src/WelsThreadLib.obj codec/common/src/WelsThreadPool.obj codec
/common/arm/copy_mb_neon.obj codec/common/arm/deblocking_neon.obj codec/common/a
rm/expand_picture_neon.obj codec/common/arm/intra_pred_common_neon.obj codec/com
mon/arm/mc_neon.obj codec/decoder/core/x86/dct.obj codec/decoder/core/x86/intra_
pred.obj codec/decoder/core/arm/block_add_neon.obj codec/decoder/core/arm/intra_
pred_neon.obj codec/decoder/core/arm64/block_add_aarch64_neon.obj codec/decoder/
core/arm64/intra_pred_aarch64_neon.obj codec/decoder/core/src/au_parser.obj code
c/decoder/core/src/bit_stream.obj codec/decoder/core/src/cabac_decoder.obj codec
/decoder/core/src/deblocking.obj codec/decoder/core/src/decode_mb_aux.obj codec/
decoder/core/src/decode_slice.obj codec/decoder/core/src/decoder.obj codec/decod
er/core/src/decoder_core.obj codec/decoder/core/src/decoder_data_tables.obj code
c/decoder/core/src/error_concealment.obj codec/decoder/core/src/fmo.obj codec/de
coder/core/src/get_intra_predictor.obj codec/decoder/core/src/manage_dec_ref.obj
 codec/decoder/core/src/memmgr_nal_unit.obj codec/decoder/core/src/mv_pred.obj c
odec/decoder/core/src/parse_mb_syn_cabac.obj codec/decoder/core/src/parse_mb_syn
_cavlc.obj codec/decoder/core/src/pic_queue.obj codec/decoder/core/src/rec_mb.ob
j codec/decoder/plus/src/welsDecoderExt.obj codec/decoder/core/arm/block_add_neo
n.obj codec/decoder/core/arm/intra_pred_neon.obj codec/encoder/core/x86/coeff.ob
j codec/encoder/core/x86/dct.obj codec/encoder/core/x86/intra_pred.obj codec/enc
oder/core/x86/matrix_transpose.obj codec/encoder/core/x86/memzero.obj codec/enco
der/core/x86/quant.obj codec/encoder/core/x86/sample_sc.obj codec/encoder/core/x
86/score.obj codec/encoder/core/arm/intra_pred_neon.obj codec/encoder/core/arm/i
ntra_pred_sad_3_opt_neon.obj codec/encoder/core/arm/memory_neon.obj codec/encode
r/core/arm/pixel_neon.obj codec/encoder/core/arm/reconstruct_neon.obj codec/enco
der/core/arm/svc_motion_estimation.obj codec/encoder/core/arm64/intra_pred_aarch
64_neon.obj codec/encoder/core/arm64/intra_pred_sad_3_opt_aarch64_neon.obj codec
/encoder/core/arm64/memory_aarch64_neon.obj codec/encoder/core/arm64/pixel_aarch
64_neon.obj codec/encoder/core/arm64/reconstruct_aarch64_neon.obj codec/encoder/
core/arm64/svc_motion_estimation_aarch64_neon.obj codec/encoder/core/src/au_set.
obj codec/encoder/core/src/deblocking.obj codec/encoder/core/src/decode_mb_aux.o
bj codec/encoder/core/src/encode_mb_aux.obj codec/encoder/core/src/encoder.obj c
odec/encoder/core/src/encoder_data_tables.obj codec/encoder/core/src/encoder_ext
.obj codec/encoder/core/src/get_intra_predictor.obj codec/encoder/core/src/md.ob
j codec/encoder/core/src/mv_pred.obj codec/encoder/core/src/nal_encap.obj codec/
encoder/core/src/picture_handle.obj codec/encoder/core/src/ratectl.obj codec/enc
oder/core/src/ref_list_mgr_svc.obj codec/encoder/core/src/sample.obj codec/encod
er/core/src/set_mb_syn_cabac.obj codec/encoder/core/src/set_mb_syn_cavlc.obj cod
ec/encoder/core/src/slice_multi_threading.obj codec/encoder/core/src/svc_base_la
yer_md.obj codec/encoder/core/src/svc_enc_slice_segment.obj codec/encoder/core/s
rc/svc_encode_mb.obj codec/encoder/core/src/svc_encode_slice.obj codec/encoder/c
ore/src/svc_mode_decision.obj codec/encoder/core/src/svc_motion_estimate.obj cod
ec/encoder/core/src/svc_set_mb_syn_cabac.obj codec/encoder/core/src/svc_set_mb_s
yn_cavlc.obj codec/encoder/core/src/wels_preprocess.obj codec/encoder/core/src/w
els_task_base.obj codec/encoder/core/src/wels_task_encoder.obj codec/encoder/cor
e/src/wels_task_management.obj codec/encoder/plus/src/welsEncoderExt.obj codec/e
ncoder/core/arm/intra_pred_neon.obj codec/encoder/core/arm/intra_pred_sad_3_opt_
neon.obj codec/encoder/core/arm/memory_neon.obj codec/encoder/core/arm/pixel_neo
n.obj codec/encoder/core/arm/reconstruct_neon.obj codec/encoder/core/arm/svc_mot
ion_estimation.obj codec/processing/src/x86/denoisefilter.obj codec/processing/s
rc/x86/downsample_bilinear.obj codec/processing/src/x86/vaa.obj codec/processing
/src/arm/adaptive_quantization.obj codec/processing/src/arm/down_sample_neon.obj
 codec/processing/src/arm/pixel_sad_neon.obj codec/processing/src/arm/vaa_calc_n
eon.obj codec/processing/src/arm64/adaptive_quantization_aarch64_neon.obj codec/
processing/src/arm64/down_sample_aarch64_neon.obj codec/processing/src/arm64/pix
el_sad_aarch64_neon.obj codec/processing/src/arm64/vaa_calc_aarch64_neon.obj cod
ec/processing/src/adaptivequantization/AdaptiveQuantization.obj codec/processing
/src/backgrounddetection/BackgroundDetection.obj codec/processing/src/common/mem
ory.obj codec/processing/src/common/WelsFrameWork.obj codec/processing/src/commo
n/WelsFrameWorkEx.obj codec/processing/src/complexityanalysis/ComplexityAnalysis
.obj codec/processing/src/denoise/denoise.obj codec/processing/src/denoise/denoi
se_filter.obj codec/processing/src/downsample/downsample.obj codec/processing/sr
c/downsample/downsamplefuncs.obj codec/processing/src/imagerotate/imagerotate.ob
j codec/processing/src/imagerotate/imagerotatefuncs.obj codec/processing/src/sce
nechangedetection/SceneChangeDetection.obj codec/processing/src/scrolldetection/
ScrollDetection.obj codec/processing/src/scrolldetection/ScrollDetectionFuncs.ob
j codec/processing/src/vaacalc/vaacalcfuncs.obj codec/processing/src/vaacalc/vaa
calculation.obj codec/processing/src/arm/adaptive_quantization.obj codec/process
ing/src/arm/down_sample_neon.obj codec/processing/src/arm/pixel_sad_neon.obj cod
ec/processing/src/arm/vaa_calc_neon.obj common.lib decoder.lib encoder.lib proce
ssing.lib openh264.lib openh264.dll  _.lib *.a *.dylib *.dll *.so *.exe *.pdb *.
exp *.pc *.res *.map
cl -O2 -Ob1 -Oy- -Zi -GF -Gm- -GS -Gy -DNDEBUG -MD -DNDEBUG -DHAVE_NEON -nologo
-W3 -EHsc -fp:precise -Zc:wchar_t -Zc:forScope -D_VARIADIC_MAX=10 -DUNICODE -DWI
NAPI_FAMILY=WINAPI_FAMILY_PHONE_APP -DWINDOWS_PHONE -DGENERATED_VERSION_HEADER -
ZW -wd4447 -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc   -c -Focod
ec/common/src/common_tables.obj codec/common/src/common_tables.cpp
common_tables.cpp
codec/common/src/common_tables.cpp: fatal error C1107: could not find assembly '
platform.winmd': please specify the assembly search path using /AI or by setting
 the LIBPATH environment variable
make: *_\* [codec/common/src/common_tables.obj] Error 2
copying dll files to destination folder...
FullDestDir is F:\openh264-master\bin\ARM\Release
current dir is:
F:\openh264-master
DestDir is bin/ARM/Release
cp: cannot stat `openh264.dll': No such file or directory
cp: cannot stat`openh264.lib': No such file or directory
cp: cannot stat `openh264.pdb': No such file or directory
cp: cannot stat`ut.dll': No such file or directory
 BuildDebugFlag   =1
 BuildReleaseFlag =1
 BuildDebugInfo   ="build debug--failed"
 BuildReleaseInfo ="build release--failed"
The system cannot find the batch label specified - GetFinalReturnCode
 ReturnCode is

F:\openh264-master\build>

**Comment by mstorsjo** [comment] 2016-05-20 06:37
Is your build toolchain actually a 64 bit toolchain? In that case, try doing `make ARCH=x86_64` instead.

**Comment by soliton4** [comment] 2016-05-20 09:53
i appear to have a similar problem
i have mingw installed,
i open a cmd from within visual studio and run the recommended .bat file to initialize the environment variables

i try to build like this:
make ARCH=x86_64 OS=msvc

it results in the following error:

fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'
make: *** [common.lib] Error 88

**Comment by mstorsjo** [comment] 2016-05-20 10:02
@soliton4 That might be a different issue. Have you tried building before in a different configuration? In that case, run `make ARCH=x86_64 OS=msvc clean` first. (Be sure to include the same options that you'll be using for building later.)

Also make sure that the bat file for initializing the environment worked as intended; if you run `cl`, does it say `x64`?

**Comment by soliton4** [comment] 2016-05-20 10:08
hi @mstorsjo and thank you for trying to help me out

calling cl gives me this output

``` C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools>cl
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
```

i am not sure if it is what should be expected

**Comment by mstorsjo** [comment] 2016-05-20 10:11
No, that is not what you should have. This means that you've got the path set up for 32 bit cl.exe. You need to run the right bat file to make sure that this should `for x64` first.

**Comment by soliton4** [comment] 2016-05-20 10:21
that was a pro tip!

i was missing this crucial information:
https://msdn.microsoft.com/en-us/library/x4d2c09s.aspx

not only do you have to init your vs variables you also have to specify your platform while doing so.

it seems like an update of the wiki page may be helpful

shall i do it?

thx again ;)

**Comment by soliton4** [comment] 2016-05-20 12:10
@XeonG have a very close look at the windows section of the wiki
the only way i got a usable dll in windows is by using the os=msvc target

it is way more complicated than just running a make

you have to start your cmd from within visual studio, and run a batchfile to initialize the correct set of environment variables.
see my previous post.

then you have to pass both OS and ARCH parameters to specify what kind of build you want to do

good luck!

**Comment by XeonG** [comment] 2016-06-22 10:58
Can someone just do these builds... I really don't have the interest in compiling all these platforms and it seems cisco can't be arsed even though the last release was last year for 1.5

for me I just need windows, but it would be good to also have android and linux builds to test with some of the newer fixes.. they really should get some sort of build system setup for more regular releases. Not everyone is into this mess of compiling for multiple platforms. Also for third parties.... going by the license I have to set it up so they download the binaries directly, so even if I do compile this crap manually... I can't going by the stupid license ship any of the latest files required for decoding/encoding.

**Comment by soliton4** [comment] 2016-06-22 11:43
@XeonG i am looking forward to how far your attitude will get you. seriously im curious ;)

**Comment by XeonG** [comment] 2016-06-25 05:47
if cisco cant be bothered todo updated release builds then it will just drive developers to using alternatives. 

the whole idea of forcing your users to have to download the binary releases is fking stupid anyway, so its less work for me not supporting it. And 1.5 is buggy and given it was released last year i'd imagine some of those bugs were fixed by now, but its no sweat off my back to not bother with it. And informing them of that is the least i can do, as it doesn't even compare to the amount of wasted time and hassle to compile out different builds to test and see if anything has been fixed, especially when developers can't even distribute those updated builds with the software anyway.

so stay curious what the hell do i care

**Comment by HaiboZhu** [comment] 2016-06-28 03:30
Thanks for all of your supports on openh264 project.
(1) about the binary release, Cisco only covering the royalties that would apply to the binary module under MPEG LA's AVC/H.264 patent pool.
(2) about the old 1.5 release, we will release the latest v1.6 recently.

**Comment by huili2** [comment] 2017-03-14 06:48
if no update on this, will close this days afterwards.

**Closed** 2017-03-21 03:00 UTC
Labels: answered
