### ISSUE TITLE
Issue with bitrate control

### ISSUE THREAD

**Issue by divyahs** [cisco/openh264#2451] opened 2016-04-27 06:47 UTC
hello,
          I am having issue related to bit rate control, not able to achieve set bit rate. Currently bit rate mode is enabled.

My encoder initialization

sSvcParam.iTemporalLayerNum                = 1; 
sSvcParam.bEnableFrameCroppingFlag   = 1; 
sSvcParam.iTargetBitrate                          = 1300 * 1000;
sSvcParam.fMaxFrameRate                      = 30.0;
sSvcParam.eSpsPpsIdStrategy                 = CONSTANT_ID; 
sSvcParam.iEntropyCodingModeFlag       = 0; 
sSvcParam.uiMaxNalSize                          = 0; 
sSvcParam.iLoopFilterDisableIdc              = 0;  
sSvcParam.iLoopFilterAlphaC0Offset       = 3; 
sSvcParam.iLoopFilterBetaOffset             = 3; 
sSvcParam.iMultipleThreadIdc                  = 1; 
sSvcParam.bUseLoadBalancing               = true; 
sSvcParam.iMaxQp                                   = 51;
sSvcParam.iMinQp                                    = 0;   
sSvcParam.bEnableDenoise                     = false;
sSvcParam.bEnableSceneChangeDetect = true;
sSvcParam.bEnableBackgroundDetection= true;
sSvcParam.bEnableAdaptiveQuant          = true;
sSvcParam.bEnableFrameSkip                 = false;
sSvcParam.bEnableLongTermReference = true;
sSvcParam.iLtrMarkPeriod                        = 30;
sSvcParam.bPrefixNalAddingCtrl              = false;
sSvcParam.iSpatialLayerNum                   = 1;
sSvcParam.iMultipleThreadIdc                  = 1;
sSvcParam.iRCMode                                = 1; // bitrate mode

pDLayer  = &sSvcParam.sSpatialLayers[0];
pDLayer->iVideoWidth   = 640;
pDLayer->iVideoHeight  = 480;
pDLayer->fFrameRate   = 30;
pDLayer->uiProfileIdc     = PRO_BASELINE;

pDLayer->iDLayerQp            = 24;
pDLayer->iSpatialBitrate       = 1300 * 1000;
pDLayer->iMaxSpatialBitrate = 1300 * 1000;

pDLayer->sSliceArgument.uiSliceMode                = SM_SIZELIMITED_SLICE;
pDLayer->sSliceArgument.uiSliceSizeConstraint  = 900; // Slice size

am I doing wrong in initialization? How to control bitrate and which parameters effect on bitrate ?

**Comment by ruil2** [comment] 2016-04-27 07:20
Could you attach the trace output? I can check why it is. thanks!

**Comment by divyahs** [comment] 2016-04-28 05:56
thanks for the reply, please can you let me know how to get trace output?

**Comment by ruil2** [comment] 2016-04-28 06:04
openh264 trace will output to console terminal in default.

and you can set the trace level by calling SetOption as below.
pPtrEnc->SetOption (ENCODER_OPTION_TRACE_LEVEL, &g_LevelSetting);

**Comment by divyahs** [comment] 2016-04-28 07:16
As your requested i attached output trace for resolution 640x480  with set bit rate 1300 kbps, thanks in advance waiting for the reply 
[trace_output.txt](https://github.com/cisco/openh264/files/239971/trace_output.txt)

[bitrate.txt](https://github.com/cisco/openh264/files/239974/bitrate.txt)

**Comment by ruil2** [comment] 2016-04-28 07:28
your trace is not complete，I didn't see the openh264 parameters configure from openh264 trace output.

but from your trace, I see the each frame estimation is 2000bps, so your target bitrate should be 600kbps. could you double check your configure? thanks!

**Comment by XeonG** [comment] 2016-05-08 04:23
I was just testing out https://github.com/unity3d-jp/FrameCapturer   unity is free to use if u want to try it yourself... 

anyway it uses version 1.5 of this codec (more recent release version compiles would be good, i think its a bit ridicilous how the user has to download the dll.. as opposed to allowing developers to publish there game with the encoders for different platforms already bundled but whatever) .. anyway the problem is the video bitrate settings makes absolutely zero difference to the encoded output quality. ie when playing back the encoded video the bitrates start low and go up only so far it has no barring on the video bitrate I set it to encode at.. I probably wouldn't mind if the default bitrate video quality wasn't so poor

**Comment by andrewmabc** [comment] 2016-06-22 03:53
I have the same issue for version 1.5.0. It's expected to produce 4.5 mbps, but indeed 384 kbps. Please refer to configuration files and trace log for detail. Is there something wrong with rate control algorithm.



[layer0.txt](https://github.com/cisco/openh264/files/326958/layer0.txt)
[layer1.txt](https://github.com/cisco/openh264/files/326961/layer1.txt)
[layer2.txt](https://github.com/cisco/openh264/files/326962/layer2.txt)
[openh264_encoder.txt](https://github.com/cisco/openh264/files/326960/openh264_encoder.txt)
[welsenc.txt](https://github.com/cisco/openh264/files/326959/welsenc.txt)

**Comment by ruil2** [comment] 2016-06-22 05:56
@andrewmabc fixed in #2504.

if you want bitrate is very accurate, you can turn off adaptive quant. (EnableAdaptiveQuantization			0 in the configure file).

**Closed by ruil2** 2016-06-22 05:56 UTC

**Comment by andrewmabc** [comment] 2016-06-23 03:07
After turning off adaptive quant, openh264 encoder still had problems, which reported :

EncodeFrame(), ret: 3, frame index: 1788.
EncodeFrame(), ret: 3, frame index: 1789.
EncodeFrame(), ret: 3, frame index: 1790.
EncodeFrame(), ret: 3, frame index: 1791.
EncodeFrame(), ret: 3, frame index: 1792.
EncodeFrame(), ret: 3, frame index: 1793.
EncodeFrame(), ret: 3, frame index: 1794.
EncodeFrame(), ret: 3, frame index: 1795.
EncodeFrame(), ret: 3, frame index: 1796.
EncodeFrame(), ret: 3, frame index: 1797.
EncodeFrame(), ret: 3, frame index: 1798.
EncodeFrame(), ret: 3, frame index: 1799.

**Comment by ruil2** [comment] 2016-06-23 03:08
which version is used in your testing?
