### ISSUE TITLE
unable to link against libopenh264-1.1.0-android19.so

### ISSUE THREAD

**Issue by mailgate** [cisco/openh264#1677] opened 2014-12-28 08:13 UTC
trying to compile & link application leads here:
/usr/bin/ld: warning: libstdc++.so, needed by /usr/lib/arm-linux-gnueabihf/libopenh264.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libc.so, needed by /usr/lib/arm-linux-gnueabihf/libopenh264.so, not found (try using -rpath or -rpath-link)
/usr/lib/arm-linux-gnueabihf/libopenh264.so: undefined reference to `__errno'
/usr/lib/arm-linux-gnueabihf/libopenh264.so: undefined reference to `__sF'
/usr/lib/arm-linux-gnueabihf/libopenh264.so: undefined reference to `__assert2'
collect2: error: ld returned 1 exit status

Makefile's LFLAGS += -L/usr/local/lib -lpthread -ludev -lfreetype -lz -lconfig -lm -lopenh264

**Comment by sijchen** [comment] 2015-01-04 05:20
Hi @mailgate , the problem seems related to environmental problem, and seems that it goes well under some other environment? On which linux and which ndk does the problem occur? Thx.

**Comment by mailgate** [comment] 2015-01-04 13:33
Hi @sijchen!
I'm trying to utilise the lib in odroid-u3 platform (uname: Linux U3 3.8.13.27 #2 SMP PREEMPT Sun Aug 24 09:15:17 PDT 2014 armv7l armv7l armv7l GNU/Linux) environment. Its not an Android...

**Comment by sijchen** [comment] 2015-01-06 02:07
@mailgate , in your title you mentioned the android lib. So the problem is on linux and not Android, correct?

**Comment by mailgate** [comment] 2015-01-06 12:41
both libs present in the system:
root@U3:/usr# ldconfig  -p|grep libc.so
	libc.so.6 (libc6,hard-float, OS ABI: Linux 2.6.32) => /lib/arm-linux-gnueabihf/libc.so.6
	libc.so.6 (libc6, OS ABI: Linux 2.6.32) => /lib/arm-linux-gnueabi/libc.so.6
root@U3:/usr# ldconfig  -p|grep std
	libstdc++.so.6 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
	libgstdataprotocol-0.10.so.0 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libgstdataprotocol-0.10.so.0

I have added necessary symlinks of directories to make sure they correspond to packages, mentioned above. - result is the same.

It looks like the binary lib was compiled in corss- environment, while I try to link in native... Although I'm not an expert in such issues...

**Comment by sijchen** [comment] 2015-10-08 18:55
this is more link some system issue where the standard libs cannot be found and does not look like the codec issue

**Comment by sijchen** [comment] 2015-10-29 22:07
close this because of no update from asker.

**Closed by sijchen** 2015-10-29 22:07 UTC
Labels: answered
