### ISSUE TITLE
idr packet lost

### ISSUE THREAD

**Issue by jim12345** [cisco/openh264#1689] opened 2014-12-31 22:21 UTC
Hi.
After 1-2 hours sometimes the h264 output become gray - it is hard to explain how it looks so i attached screenshot.
It keeps like that until I stop the encoding.

I understand it is caused by IDR Packets lost???
My code use the openh264 Encoder ONLY.
Decoding is done on another device using 3rd party decoder (not openh264)
 
1) Can i detect in my code that IDR Packets have lost and then to restart the encoder?
If yes, how can i detect the IDR packet lose?
2) this image was taken when i used Encoder v1.2.
I am not sure if that still happen in encoder v1.3 (I understand you added some fixed for errors there).
Still  will your fix make the output image (after idr packet lost) as if this IDR packets lost has never happen (so no fix from my code is needed), or your fix will do some semi fix and output will not be as good as it was before the IDR packet lost 

My main goal here is to prevent having this gray image and if I can not prevent it then at least to know when that happens so my code will know to restart the encoder again.

![b630200a-8885-11e4-9efd-1e71357c2c11](https://cloud.githubusercontent.com/assets/7906839/5590945/5be63e7a-914c-11e4-855c-a4f48638062d.JPG)

**Comment by sijchen** [comment] 2015-01-04 05:05
Hi, since you are using 3rd party decoder, it is possible that this is due to error concealment done by the decoder. To make sure whether it is related OpenH264 encoder, you can try to dump the bit stream after encoding and before transmission, and send it to reference software or OpenH264 decoder to see the ourput.

**Comment by jim12345** [comment] 2015-01-04 22:27
I am sure it is not the 3rd decoder bug.
If it is not the decoder error, Can i detect in my code that IDR Packets have lost and then to restart the encoder?
I.E can i do anything from the encoder side?

**Comment by huili2** [comment] 2015-01-05 01:06
If actual packet loss happens, I assume the 3rd-party decoder can throw some error information. Then for openh264 Encoder, you can use ForceIntraFrame(), and go on encoding.
If no error information is given, I think from encoder side, you have no good choice but send IDR frame periodically.

**Comment by sijchen** [comment] 2015-01-05 06:07
I did not mean it is decoder bug, it may be the error concealment strategy it chose. My comments will be as stated before, to save the output bit stream of encoder before transmission, and put it through reference software or OpenH264 decoder to check the output, or you can send the dumped bit stream to us to check.

**Comment by jim12345** [comment] 2015-01-08 19:42
I think i can confirm it is OpenH264 encoder bug.
It happens after ~2.5 hours of encoding.
This time i let it to encode the images to h264 output that is online sent to the 3rd decoder.
When that happened (the gray images started to came) I deleted the OpenH264 encoder and re create it and continue to encode and send the output to the 3rd decoder and that fixed the issue (encoded video started to look good again).
The decoder could not have known that the encoder has been re created (unless the encoder make some specific output when you create it and send it the first image).
So if decoder did not know that encoder has been re created, and recreating the encoder make it to output good h264 then i guess that it is the encoder bug (Am I wrong?).
To duplicate it, feed the encoder with ~25 images per second (not the same images  - feed it with images from movie) for about 2.5 hours and more (for me it took encoder about 2.2 hours till that happen - it happened 3 times 100% of the time i used it after 2.3 hours).

So to sum, feed the encoder for about 3 hours with 25 images per second (different images - not the same image) - after about 2.3-2.5 hours you should see the output as the grey image i attached.

**Comment by sijchen** [comment] 2015-01-09 02:12
Hi, could you send us the configuration you use so we can try to reproduce? especially the temporal layer, LTR and intra-period settings.

**Comment by dongzha** [comment] 2015-01-09 03:18
Although your decoder did not know that encoder has been recreated, recreating the encoder will force encoding an IDR frame, which will recover the transmission error.
Your description can not confirm it is encoder bug. 
A better way is to recode the bit stream before and after transmission.

**Comment by sijchen** [comment] 2015-08-27 16:38
close this since this issue is not being updated for needed info.

**Closed by sijchen** 2015-08-27 16:38 UTC
