### ISSUE TITLE
OpenH264 / H264 not working in Firefox & can't watch some HTML5 videos.

### ISSUE THREAD

**Issue by Firefox-user** [cisco/openh264#2835] opened 2017-08-09 08:21 UTC
When trying to view the following youtube videos at this link https://www.youtube.com/user/dutchsinse
 won't play. A couple other people I know are having the same problems & trying to help them I found the same problem (there are also several others that have the same problems when one does a search online for HTML5 won't play in Firefox). I then followed the youtube link given in the unsupported window that popped up https://www.youtube.com/html5 . It as well as https://html5test.com/ show that H264 and MSE & H264 are NOT working. OpenH264 is installed and as far as I can tell is turned on/enabled (whether it is actually on/enabled & functioning I can't tell). I even followed a few instructions to check the about:config settings in Firefox & all that are said to deal with HTML5 playback are set to what they are supposed to be. In the past I didn't remember having any issues with HTML5 playback. Firefox is up to date 52.3.0esr (32bit).

Can someone please help.

**Comment by GuangweiWang** [comment] 2017-08-10 08:27
In fact, openh264 has not changed for a long time on Firefox. Have you asked Firefox for help?

**Comment by GuangweiWang** [comment] 2017-08-10 10:50
what is your platform this issue occurred on? windows-32bits? or another platform?
I can not reproduce this issue on Mac OSX

**Comment by GuangweiWang** [comment] 2017-08-11 00:48
hi @Firefox-user 
I have installed the same version Firefox(52.3.0esr 32bits) on my windows PC and tried that 3 URLs you mentioned. 
videos at this link  https://www.youtube.com/user/dutchsinse can play normally, and H264 works well on the other 2 pages.

I can not reproduce you issue on my PC environment.

**Comment by t0mciu** [comment] 2017-09-06 15:19
@Firefox-user
If you use Windows XP and FF 52 ESR see this thread:
http://www.msfn.org/board/topic/175591-enable-mp4-h264-aac-html5-video-in-firefox-on-windows-xp-without-flash/

**Comment by treba123** [comment] 2017-11-21 21:38
I can confirm this using firefox with flatpak (a new sandboxing technology on linux).
Within flatpak, there's no other h264 implementation available (I guess on Windows, Mac OS and most Linux systems firefox can simply use system decoders).

Steps to reproduce:
- an any modern linux distribution, install firefox via flatpak (https://firefox-flatpak.mojefedora.cz/)
- check https://www.youtube.com/html5

**Comment by nils-ohlmeier** [comment] 2017-11-22 00:23
Indeed the OpenH264 plugin is only used for WebRTC calls in Firefox not for playing back any H264 encoded videos outside of WebRTC. So this is not an OpenH264 issue.

**Comment by GuangweiWang** [comment] 2017-11-22 00:26
@nils-ohlmeier 
Thank you for your answer!

**Comment by marsjaninzmarsa** [comment] 2018-02-01 07:30
https://github.com/xhorak/firefox-devedition-flatpak/issues/22#issuecomment-361584033

**Comment by sijchen** [comment] 2018-02-19 21:35
close this since it is supposed to be solved in the above link.

**Closed by sijchen** 2018-02-19 21:35 UTC
