### ISSUE TITLE
Unable to make plugin

### ISSUE THREAD

**Issue by JuPlutonic** [cisco/openh264#2838] opened 2017-08-20 04:06 UTC
on a5b14c2

_4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux 
Ubuntu 16.04.2
GNU bash, versione 4.3.48(1)-release (x86_64-pc-linux-gnu)_

error when run `make OS=linux ARCH=x86_64 ENABLE64BIT=Yes plugin`
or when run with various shebangs (bash sh dash zsh) this script
`/codec/common/generate_version.sh` 
... says _error_ expected else, not end of the file...

when using template as version_gen.sh, I get:[Gist](https://gist.github.com/JuPlutonic/ee53b90fc8863556078afe6b288386ea))

**Comment by GuangweiWang** [comment] 2017-08-21 01:47
thanks for your detail information.

just have one question want to confirm with you. the log from your "Gist" is the error log after making with this command "make OS=linux ARCH=x86_64 ENABLE64BIT=Yes plugin"? if not, could you please provide the log? many thanks.

for your Gist: 
1. version_gen.h.template can not be used as version_gen.sh
2. error occurs when running this script "codec/common/generate_version.sh". that error caused by an invalid path of this file: "version_gen.h.template".  we can see that invalid prefix './'$'\r', this cause the error.  (cat: './'$'\r''/codec/common/inc/version_gen.h.template': No such file or directory)

**Comment by JuPlutonic** [comment] 2017-08-26 22:50
Hi, the answer 1)yes, but I tried 2)no error occured only on linux systems, and when I converted all git cloned code from windows line ends to unix line ends I got compiled plugin.

**Comment by JuPlutonic** [comment] 2017-08-26 22:55
- dos2unix -f */*/*/*/*/*/*/*/* && dos2unix -f */*/*/*/*/*/*/* && dos2unix -f */*/*/*/*/*/* && dos2unix -f */*/*/*/*/* && dos2unix -f */*/*/*/* && dos2unix -f */*/*/* && dos2unix -f */*/* && dos2unix -f */* dos2unix -f *
- make OS=linux DEBUGSYMBOLS=True ARCH=x86_64 ENABLE64BIT=Yes gmp-bootstrap
- make OS=linux DEBUGSYMBOLS=True ARCH=x86_64 ENABLE64BIT=Yes plugin

**Comment by JuPlutonic** [comment] 2017-08-27 22:10
Sorry, it is problem on my side...
... now I'm Seting `git config --global core.autocrlf false`

**Comment by GuangweiWang** [comment] 2017-08-28 00:31
Great. 
If it is resolved, we can close this issue then.

**Closed** 2017-08-28 02:19 UTC
