### ISSUE TITLE
checksum error for openh264 (fedora 36)

### ISSUE THREAD

**Issue by Clumsyoof** [cisco/openh264#3510] opened 2022-04-22 17:59 UTC
Got this error while trying to download and upgrade openh264

```
Errors during downloading metadata for repository 'fedora-cisco-openh264':
  - Downloading successful, but checksum doesn't match. Calculated: eb59e9e7cbde672c4321d25dcc33f5eeadcf48a6bcf3dc97740e51961ce7230e44d1108a8b93b6dabf194d7ec6ac0ee0476c112cdbc65f7e972f22d5370c89bb(sha512)  Expected: d1fe5fb20bbb0ee9f5d043ab4d463ecd6dac75de35f420efbafc2fb3481dba5d8934aa97caf1b70ed13e7cac4589f33a5f4a846ee625496648cc3391774c359c(sha512) 
Error: Failed to download metadata for repo 'fedora-cisco-openh264': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: fedora-cisco-openh264
```

**Comment by MaxwellDupre** [comment] 2022-08-25 10:43
Im getting same.
In the  fedora discussion Adrian Reber commented:
Should be fixed now. There is a bug in one of the tools creating this. The bug is fixed but not yet deployed because of the current infrastructure freeze.
Is there a workaround like build from source? DNF command?

**Comment by LeSeskyCar** [comment] 2022-08-25 15:13
I am also facing this same issue

**Comment by owocean** [comment] 2022-08-25 16:56
fresh fedora 36 install today, same error. wake up wake up wake up wake up wake up wake up

**Comment by Pairman** [comment] 2022-08-25 21:19
Same issue for me. Looking for a fix

**Comment by LeSeskyCar** [comment] 2022-08-26 14:31
Well, now it works for me, I gave up yesterday and was planning to reinstall it today, but when I turned it on, it just worked.

**Comment by owocean** [comment] 2022-08-26 14:39
same i think it was just an issue with the mirror

**Comment by GuangweiWang** [comment] 2022-08-29 06:13
the fedora 36 has been updated for openh264 2.3.0, please try again to check if this issue has been resolved.

**Comment by Pairman** [comment] 2022-08-29 09:48
> the fedora 36 has been updated for openh264 2.3.0, please try again to check if this issue has been resolved.

The issue is reolved several hrs after that, it's ok now.

**Comment by GASOLINE** [comment] 2022-08-29 09:51
> the fedora 36 has been updated for openh264 2.3.0, please try again to check if this issue has been resolved.

Problem solved. Thanks.

**Comment by MaxwellDupre** [comment] 2022-08-29 10:12
works for me thanks.

**Comment by GuangweiWang** [comment] 2022-08-30 01:09
greate.

**Comment by GuangweiWang** [comment] 2022-08-30 01:10
if there is no update, this issue will be closed later.

**Comment by Clumsyoof** [comment] 2022-09-01 11:01
> the fedora 36 has been updated for openh264 2.3.0, please try again to check if this issue has been resolved.

Issue is resolved now, thanks !

**Closed** 2022-09-01 12:22 UTC
