### ISSUE TITLE
How to lower quality to keep constant framerate ?

### ISSUE THREAD

**Issue by Maypeur** [cisco/openh264#2308] opened 2015-12-11 13:23 UTC
Hello,

I use OpenH264 with FFmpeg.
I would like my stream keep always the same framerate and a maximum bitrate by lowering the quality if needed.

But, even if FFmpeg force bEnableFrameSkip to 0 and only max_rate is set correctly, OpenH264 bypass the bitrate limit and lower the framerate.

I'm trying to do live streaming that's why i always would keep same framerate and limit the bitrate. 

Sorry to tell you that, but with x264 max_rate and time_base are well respected.

Is there any parameters that i can adjust or is this functionnality is not yet implemented ?

PS: does iRCMode = RC_BITRATE_MODE; is related to this ?

Anyway, thanks for this library !

**Comment by volvet** [comment] 2016-01-05 07:36
you can set    bEnableFrameSkip = false when you create encoder,    bEnableFrameSkip can be found in structure TagEncParamExt.      
Or,   option ENCODER_OPTION_RC_FRAME_SKIP can help you in runtime.

**Comment by ruil2** [comment] 2016-01-06 01:55
Could you list your all settings?

**Comment by FAHADSUST** [comment] 2016-01-06 05:01
encParam.iUsageType = CAMERA_VIDEO_REAL_TIME;
	encParam.iTemporalLayerNum = 0;
	encParam.uiIntraPeriod = 8;
	encParam.eSpsPpsIdStrategy = INCREASING_ID;
	encParam.bEnableSSEI = false;
	encParam.bEnableFrameCroppingFlag = true;
	encParam.iLoopFilterDisableIdc = 0;
	encParam.iLoopFilterAlphaC0Offset = 0;
	encParam.iLoopFilterBetaOffset = 0;
	encParam.iMultipleThreadIdc = 0;
	encParam.iRCMode = RC_BITRATE_MODE;
	encParam.bEnableDenoise = false;
	encParam.bEnableSceneChangeDetect = false;
	encParam.bEnableBackgroundDetection = true;
	encParam.bEnableAdaptiveQuant = false;
	encParam.bEnableFrameSkip = true;
	encParam.bEnableLongTermReference = true;
	encParam.iLtrMarkPeriod = 20;
	encParam.bPrefixNalAddingCtrl = false;
	encParam.iSpatialLayerNum = 1;
	encParam.iComplexityMode = LOW_COMPLEXITY;

	SSpatialLayerConfig *pDLayer = &encParam.sSpatialLayers[0];
	pDLayer->uiProfileIdc = PRO_BASELINE;
	encParam.iPicWidth = pDLayer->iVideoWidth = m_iWidth;
	encParam.iPicHeight = pDLayer->iVideoHeight = m_iHeight;
	encParam.fMaxFrameRate = pDLayer->fFrameRate = (float)30;
	encParam.iTargetBitrate = pDLayer->iSpatialBitrate = BITRATE_MAX;
	pDLayer->iMaxSpatialBitrate = UNSPECIFIED_BIT_RATE;
	pDLayer->iDLayerQp = 24;
	pDLayer->sSliceCfg.uiSliceMode = SM_SINGLE_SLICE;

**Comment by ruil2** [comment] 2016-01-06 06:49
Two suggestions on the setting.

  1.

iTemporalLayerNum should be 1 or other value(which is less than 4)

  2.

You can set iMaxQp and iMinQp to balance quality and bitrate.

  I am not sure whether the range of QP is the root cause. If still have questions, it is better to give the openh264 output info to us. Thanks!

**Comment by Maypeur** [comment] 2016-01-06 07:48
Thanks for your complete response !

So If i understand, i have to use all the encParam listed above ?
Or, does all theses parameters must be set to keep framerate or only a few like :
encParam.iRCMode = RC_BITRATE_MODE; and encParam.iTemporalLayerNum = 0; ?

**Comment by ruil2** [comment] 2016-01-08 02:16
if you only want to keep the frame rate. you don't need to set all the parameters.
but the below parameters should be set. 
1. encParam.bEnableFrameSkip = false;
2. keep the same value for encParam.fMaxFrameRate and pDLayer->fFrameRate.

**Comment by HaiboZhu** [comment] 2016-03-30 01:35
No update for long time, close it.

**Closed by HaiboZhu** 2016-03-30 01:35 UTC
Labels: answered
