### ISSUE TITLE
EncodeFrame may wait forever and not quit in openh264 v1.7.1 for Apple platform

### ISSUE THREAD

**Issue by PeterXu** [cisco/openh264#2781] opened 2017-07-19 01:21 UTC
In v1.7.1,  Replace sema with "pthread_cond_t" for  thread pool in apple platform.
However, there exists possible issues:
    pthread_cond_signal only works when pthread_cond_wait has been called and is waiting.

So pthread_cond_signal is called before pthread_cond_wait executes, then pthread_cond_wait will not quit and wait for next pthread_cond_signal.

That is why pthread_cond_t should be used and combined with pthread_mutex_t:
pthread_mutex_lock()
pthread_cond_wait()/pthread_cond_signal()
pthread_cond_unlock()

e.g.  The call of WelsEventWait  in CWelsTaskManageBase::ExecuteTaskList may wait and not quit.

**Comment by sijchen** [comment] 2017-07-31 04:18
@PeterXu , thanks a lot for this issue. We do try to avoid that by calling "pthread_mutex_lock" before "pthread_cond_wait" here https://github.com/cisco/openh264/blob/master/codec/common/src/WelsThreadLib.cpp#L364, 
could you kindly take a look or give us an example on how the things can get stuck? Thanks a lot!

**Comment by PeterXu** [comment] 2017-08-01 01:49
@sijchen , That means extra counter is used to replace cond-self, I think that works but a little ugly.

In this "CWelsTaskManageBase::ExecuteTaskList", When QueueTask(forloop) is called and done(OnTaskMinusOne is called),  but WelsEventWait may still not called.
This often happens in my testing(multi-spatial layers).

One suggestion,

In order to resolve it by native pthread_cond_t, the thread model of thread pool should be changed:
From "thread-pool allocates task to threads" to "thread get task from thread-pool queue automatically".

This is one case in my testing and it works well (based-on v1.7.1).

[0001-fix-threadpool-dead-lock.patch.txt](https://github.com/cisco/openh264/files/1189289/0001-fix-threadpool-dead-lock.patch.txt)

**Comment by ruil2** [comment] 2017-08-03 01:12
@PeterXu  
1. could you give us parameters setting in your testing to reproduce this issue?
2. could you submit a PR for your fix? 
thanks a lot!

**Comment by sijchen** [comment] 2017-08-08 22:19
@PeterXu 
could you give us parameters setting in your testing to reproduce this issue? so that we may add UT to cover that. 
I checked your patch file, not all changes looks relevant, so would like to find the exact case to make the changes clear. 
Thanks a lot!

**Comment by zjudongze** [comment] 2017-10-20 02:51
Is this problem fixed on commit fa26824?

**Comment by sijchen** [comment] 2017-11-28 01:12
we did try some fixes but I am not quite sure if what @PeterXu mentioned is still valid, since we don't receive any further info for debugging and we did not reproduce that yet. 

If there can be some cfg files provided and we can reproduce, we are more than happy to debug and fix.

**Comment by PeterXu** [comment] 2017-12-13 02:38
@sijchen I am sorry, further verify is still not done.

**Comment by sijchen** [comment] 2018-02-19 21:36
close this for now, can re-open if we find new evidence of fixes needed.

**Closed by sijchen** 2018-02-19 21:36 UTC

**Comment by terraslate** [comment] 2018-02-19 23:41
Nice timing actually, as noted under Windows this definitely occurs when running as a service. We switched our production code from running as a service to running as a logged in user  about a month ago because every day we run into this issue, in last month since switch not one occurrence. 

It's very easy to reproduce, just run as a Windows service (ours is called with a .Net wrapper), do lots of encodings on different threads. Watch it hang inside the encode method.
